name: Deploy
on: workflow_call

jobs:
  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push

    steps:
      - name: SSH into QA EC2 & Deploy
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          QA_EC2_IP: ${{ secrets.QA_EC2_IP }}
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem
          
          ssh -o StrictHostKeyChecking=no -i private_key.pem ec2-user@$QA_EC2_IP << 'EOF'
            # Pull new images
            docker pull ${{ secrets.AWS_ECR_URI }}/backend:latest
            docker pull ${{ secrets.AWS_ECR_URI }}/frontend:latest

            # Restart services
            DB_HOST=$DB_HOST DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD DB_NAME=$DB_NAME docker-compose -f docker-compose.yml down -v
            DB_HOST=$DB_HOST DB_USER=$DB_USER DB_PASSWORD=$DB_PASSWORD DB_NAME=$DB_NAME docker-compose -f docker-compose.yml up --build -d
          EOF