name: Main Workflow

on:
  schedule:
    - cron: '0 0 * * *' # Runs every midnight UTC
  workflow_dispatch:

jobs:
  test:
    uses: nannanav/crud-infra/.github/workflows/test.yml@main

  build-and-push:
    needs: test
    if: ${{ needs.test.outputs.test_result == '0' }}
    uses: nannanav/crud-infra/.github/workflows/build-and-push.yml@main
    # with:
    #   test_result: ${{ needs.test.outputs.test_result }}

  deploy:
    needs: build-and-push
    uses: nannanav/crud-infra/.github/workflows/deploy.yml@main